# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
Organizations:
    - &UNSP
        Name: UNSPMSP
        ID: UNSPMSP
        MSPDir: ./crypto-config/ordererOrganizations/unsp.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('UNSPMSP.member', 'UNSPMSP.admin', 'UNSPMSP.peer', 'UNSPMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('UNSPMSP.member', 'UNSPMSP.admin', 'UNSPMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('UNSPMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('UNSPMSP.peer')"
        OrdererEndpoints:
            - ordere1.unsp.example.com:7050
        AnchorPeers:
            - Host: peer0.unsp.example.com
              Port: 7051

    - &Airline1
        Name: Airline1MSP
        ID: Airline1MSP
        MSPDir: ./crypto-config/ordererOrganizations/airline1.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Airline1MSP.member', 'Airline1MSP.admin', 'Airline1MSP.peer', 'Airline1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Airline1MSP.member', 'Airline1MSP.admin', 'Airline1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Airline1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Airline1MSP.peer')"
        OrdererEndpoints:
            - orderer2.airline1.example.com:8050
        AnchorPeers:
            - Host: peer0.airline1.example.com
              Port: 8051

    - &Airline2
        Name: Airline2MSP
        ID: Airline2MSP
        MSPDir: ./crypto-config/ordererOrganizations/airline2.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Airline2MSP.member', 'Airline2MSP.admin', 'Airline2MSP.peer', 'Airline2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Airline2MSP.member', 'Airline2MSP.admin', 'Airline2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Airline2MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Airline2MSP.peer')"
        OrdererEndpoints:
            - orderer3.airline2.example.com:9050
        AnchorPeers:
            - Host: peer0.airline2.example.com
              Port: 9051

    - &Airline3
        Name: Airline3MSP
        ID: Airline3MSP
        MSPDir: ./crypto-config/ordererOrganizations/airline3.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Airline3MSP.member', 'Airline3MSP.admin', 'Airline3MSP.peer', 'Airline3MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Airline3MSP.member', 'Airline3MSP.admin', 'Airline3MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Airline3MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Airline3MSP.peer')"
        OrdererEndpoints:
            - orderer4.airline3.example.com:10050
        AnchorPeers:
            - Host: peer0.airline3.example.com
              Port: 10051

    - &Airline4
        Name: Airline4MSP
        ID: Airline4MSP
        MSPDir: ./crypto-config/ordererOrganizations/airline4.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Airline4MSP.member', 'Airline4MSP.admin', 'Airline4MSP.peer', 'Airline4MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Airline4MSP.member', 'Airline4MSP.admin', 'Airline4MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Airline4MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Airline4MSP.peer')"
        OrdererEndpoints:
            - orderer5.airline4.example.com:11050
        AnchorPeers:
            - Host: peer0.airline4.example.com
              Port: 11051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    ACLs: &ACLsDefault
        _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
        _lifecycle/QueryChaincodeDefinition: /Channel/Application/Readers
        _lifecycle/QueryNamespaceDefinitions: /Channel/Application/Readers
        lscc/ChaincodeExists: /Channel/Application/Readers
        lscc/GetDeploymentSpec: /Channel/Application/Readers
        lscc/GetChaincodeData: /Channel/Application/Readers
        lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
        qscc/GetChainInfo: /Channel/Application/Readers
        qscc/GetBlockByNumber: /Channel/Application/Readers
        qscc/GetBlockByHash: /Channel/Application/Readers
        qscc/GetTransactionByID: /Channel/Application/Readers
        qscc/GetBlockByTxID: /Channel/Application/Readers
        cscc/GetConfigBlock: /Channel/Application/Readers
        peer/Propose: /Channel/Application/Writers
        peer/ChaincodeToChaincode: /Channel/Application/Readers
        event/Block: /Channel/Application/Readers
        event/FilteredBlock: /Channel/Application/Readers    
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer1.unsp.example.com:7050
        - orderer2.airline1.example.com:8050
        - orderer3.airline2.example.com:9050
        - orderer4.airline3.example.com:10050
        - orderer5.airline4.example.com:11050
    

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    EtcdRaft:
        Consenters:
            - Host: orderer1.unsp.example.com
              Port: 7050
              ClientTLSCert: ./crypto-config/ordererOrganizations/unsp.example.com/orderers/orderer1.unsp.example.com/tls/server.crt
              ServerTLSCert: ./crypto-config/ordererOrganizations/unsp.example.com/orderers/orderer1.unsp.example.com/tls/server.crt
            - Host: orderer2.airline1.example.com
              Port: 8050
              ClientTLSCert: ./crypto-config/ordererOrganizations/airline1.example.com/orderers/orderer2.airline1.example.com/tls/server.crt
              ServerTLSCert: ./crypto-config/ordererOrganizations/airline1.example.com/orderers/orderer2.airline1.example.com/tls/server.crt
            - Host: orderer3.airline2.example.com
              Port: 9050
              ClientTLSCert: ./crypto-config/ordererOrganizations/airline2.example.com/orderers/orderer3.airline2.example.com/tls/server.crt
              ServerTLSCert: ./crypto-config/ordererOrganizations/airline2.example.com/orderers/orderer3.airline2.example.com/tls/server.crt
            - Host: orderer4.airline3.example.com
              Port: 10050
              ClientTLSCert: ./crypto-config/ordererOrganizations/airline3.example.com/orderers/orderer4.airline3.example.com/tls/server.crt
              ServerTLSCert: ./crypto-config/ordererOrganizations/airline3.example.com/orderers/orderer4.airline3.example.com/tls/server.crt
            - Host: orderer5.airline4.example.com
              Port: 11050
              ClientTLSCert: ./crypto-config/ordererOrganizations/airline4.example.com/orderers/orderer5.airline4.example.com/tls/server.crt
              ServerTLSCert: ./crypto-config/ordererOrganizations/airline4.example.com/orderers/orderer5.airline4.example.com/tls/server.crt
        Options:
            TickInterval: 500ms
            ElectionTick: 10
            HeartbeatTick: 1
            MaxInflightBlocks: 5
            SnapshotIntervalSize: 16 MB

    Organizations:
        - *UNSP
        - *Airline1
        - *Airline2
        - *Airline3
        - *Airline4

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        ConsensusType:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Creation:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # 添加通道管理策略
        ChannelCreation:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # 添加区块签名验证策略
        BlockSignature:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        ModifyPolicy:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    airspacechannel:
        Consortium: AirspaceConsortium
        <<: *ChannelDefaults
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *UNSP
                - *Airline1
                - *Airline2
                - *Airline3
                - *Airline4
            Addresses:
                - orderer1.unsp.example.com:7050
                - orderer2.airline1.example.com:8050
                - orderer3.airline2.example.com:9050
                - orderer4.airline3.example.com:10050
                - orderer5.airline4.example.com:11050
            Capabilities:
                <<: *OrdererCapabilities
            Policies:
                Readers:
                    Type: ImplicitMeta
                    Rule: "ANY Readers"
                Writers:
                    Type: ImplicitMeta
                    Rule: "ANY Writers"
                Admins:
                    Type: ImplicitMeta
                    Rule: "MAJORITY Admins"
                BlockValidation:
                    Type: ImplicitMeta
                    Rule: "ANY Writers"
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *UNSP
                - *Airline1
                - *Airline2
                - *Airline3
                - *Airline4
            Capabilities:
                <<: *ApplicationCapabilities
            Policies:
                Readers:
                    Type: ImplicitMeta
                    Rule: "ANY Readers"
                Writers:
                    Type: ImplicitMeta
                    Rule: "ANY Writers"
                Admins:
                    Type: ImplicitMeta
                    Rule: "MAJORITY Admins"
                LifecycleEndorsement:
                    Type: ImplicitMeta
                    Rule: "MAJORITY Endorsement"
                Endorsement:
                    Type: ImplicitMeta
                    Rule: "MAJORITY Endorsement"

    OrdererGenesis:
        <<: *ChannelDefaults
        Consortiums:
            AirspaceConsortium:
                Organizations:
                    - *UNSP
                    - *Airline1
                    - *Airline2
                    - *Airline3
                    - *Airline4
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *UNSP
                - *Airline1
                - *Airline2
                - *Airline3
                - *Airline4
            Capabilities:
                <<: *OrdererCapabilities
            Policies:
                Readers:
                    Type: ImplicitMeta
                    Rule: "ANY Readers"
                Writers:
                    Type: ImplicitMeta
                    Rule: "ANY Writers"
                Admins:
                    Type: ImplicitMeta
                    Rule: "MAJORITY Admins"
                BlockValidation:
                    Type: ImplicitMeta
                    Rule: "ANY Writers"
